### PR TITLE
docs: update README.md

### LINKED ISSUE #184: Broken link in REDME.md
[Issuehunt badges](https://issuehunt.io/r/lc-soft/LCUI/issues/184)

**Describe the bug**
The `README.md` mentions a link to the `CONTRIBUTING.md` but that file doesn't exist.
See here: https://github.com/lc-soft/LCUI/blob/develop/README.md#contribution

It sends to this https://github.com/lc-soft/LCUI/blob/develop/CONTRIBUTING.md which is a 404

I would love to contribute to this project but I need instructions to set up the Development Environment.

**Expected behavior**
Sends the developer to documentation for getting started to contribute to your project. Have a look here.

**Screenshots**
Screenshot from 2019-10-19 14-37-24

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $2.00)

- [lc-soft lc-soft](https://issuehunt.io/u/lc-soft) ($2.00)
### Submitted pull Requests
- [#185 docs: update README.md](https://issuehunt.io/r/lc-soft/LCUI/pull/185)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/lc-soft/LCUI/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by anshulxyz**
Fixes #184

Changes proposed in this pull request:
- Update the broken link to Contributing file
- Update a minor grammatical error

@lc-soft

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#184: Broken link in REDME.md](https://issuehunt.io/repos/5293802/issues/184)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by anshulxyz** [comment]
Docs files, should not be subjected to coverage :thinking:

**Comment by lc-soft** [comment]
OK, I mistakenly believe that github will automatically link CNTRIBUTING.md to .github/CNTRIBUTING.md.

**Comment by anshulxyz** [comment]
you should also take a look at https://coveralls-python.readthedocs.io/en/latest/tips/coveragerc.html to build a config file for Coveralls-Coverage so that it doesn't track documentations and other unnecessary files.

**Comment by lc-soft** [comment]
@anshulxyz you can do it, please create a issue, I will fund it.

**Comment by anshulxyz** [comment]
@lc-soft ok :pray: I will do it

**Pull request merged**
